### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TheBiblMan** [bobbylight/RSyntaxTextArea#105]
I'm receiving this error:
http://hastebin.com/ebuseqipam.avrasm
```java
		textArea = new RSyntaxTextArea() {
			private static final long serialVersionUID = 2771137817070116930L;

			@Override
			public void setText(String s) {
				System.out.println("-----------adding: ");
				System.out.println(s);
				System.out.println("-------------end adding");
				super.setText(s);
				SwingUtilities.invokeLater(RESET_VIEW_RUNNABLE);
			}
		};

		((RSyntaxTextArea) textArea).setAntiAliasingEnabled(true);

		scrollPane = new RTextScrollPane(textArea);
		add(scrollPane);
```
Any ideas?

**Comment by bobbylight** [comment]
It means the editor's contents broke RSTA's current parser (in your case, plain text).  My guess would be you have some non-printable or otherwise odd character that the parser is choking on.  This shouldn't happen, however - we should be able to handle all input.

I tried manually opening RSTA and copy-pasting the contents in your editor as implied by http://hastebin.com/ebuseqipam.avrasm, but I did not get the error you did.  Can you create a text file that, when opening in RSTA, causes this problem?  If so then I could use that to identify the problem.

**Comment by TheBiblMan** [comment]
Ok, so I'm using RSyntaxTextArea for my IDE and was generating text at runtime and adding it a text area and then adding that to the view, however now instead of generating it on the fly, i'm loading it from the projects source code directory and its working fine
```java
	@Override
	public String decompile(PrefixedStringBuilder sb, ClassNode cn) {
		File f = new File(srcFolder, cn.name + ".bytecode");
		if (f.exists()) {
			try {
				return IOManager.read(f);
			} catch (IOException e) {
				e.printStackTrace();
			}
		} else {
			System.out.println(String.format("doesn't exist%s", f.getAbsolutePath()));
		}
		buildClassNodeRepresentation(sb = new PrefixedStringBuilder(), cn.name, cn);
		return sb.toString();
	}
```
And it apparently works completely fine. Thanks for the help man (and awesome project)!
