### ISSUE TITLE
Feature Request: Enable the current line to be highlighted in the gutter

### ISSUE THREAD

**Issue by joelmoniz** [bobbylight/RSyntaxTextArea#124]
For example, like so:

![highlight current line in gutter](http://i210.photobucket.com/albums/bb180/pics_freakazoida/highlight.png)

Would it also be possible to allow customization of the highlight colour, something analogous to the RSyntaxTextArea.setCurrentLineHighlightColor() method, but for the Gutter?

**Comment by bobbylight** [comment]
I'm not interested in implementing this.  RSTA used to behave this way, but I took it out purely because of personal preference.  Pull requests are welcome if you are interested in adding this feature, but it would have to be the case that:

* It was an option to toggle this setting on and off
* It works appropriately when line wrap is enabled (and thus line numbers are not always evenly spaced)
* It works properly with code folding taken into account

Unit tests would be a huge bonus as well.

**Comment by joelmoniz** [comment]
Thank you. I shall take a shot at sending in a PR that implements this soon.
