### ISSUE TITLE
Monokai Theme

### ISSUE THREAD

**Issue by Immortalin** [bobbylight/RSyntaxTextArea#135]
Can you add a monokai theme similar to the one in Sublime Text?

**Comment by JonSn0w** [comment]
I had implemented a monokai-styled theme within my program manually, as I've been having trouble with the InputStream when I tried importing themes via XML. Nevertheless, I did my best to put together a XML theme file that I believe should do the trick, though until I fix my InputStream issue I'm not currently able to test it.
[monokai.zip](https://github.com/bobbylight/RSyntaxTextArea/files/301355/monokai.zip)

**Comment by bobbylight** [comment]
I merged the pull request, thanks.  I did take the rather authoritarian measure of changing the "roundedEdges" property to false, since they look funny (in my opinion) and sometimes leave visual artifacts in RSTA.  I figure it's one line to re-enable it, and the color scheme is the most important bit here.
