### ISSUE TITLE
RSyntaxTextArea mark occurrences problem

### ISSUE THREAD

**Issue by bojanvukotic** [bobbylight/RSyntaxTextArea#149]
I have RSyntaxTextArea where I set setMarkOccurrences(true); 
Problem is following: in some cases text area gets grayed, usually in this situation: I type some text and that press ctrl + A and then 'delete'. All text is deleted but editor is grayed. When I turn off option to mark occurrences problem is gone. Looks like RSyntaxTextArea  is trying to mark occurrence of empty string (or something like that). I am using version 2.5.7
Note: I have syntax highlight for my language, but I am also able to reproduce a problem when using SQL syntax style (images bellow show bug when using sql syntax style, first situation occurs after autocomplete, second one after deleting all chars)

![bug_1](https://cloud.githubusercontent.com/assets/15214192/10609122/6d96e52a-7742-11e5-9c99-5f39fdb8f40a.png)
![bug_2](https://cloud.githubusercontent.com/assets/15214192/10609123/6d98e848-7742-11e5-8369-ea7ef8c7ff85.png)

**Comment by bobbylight** [comment]
I am aware of some problems with the "mark occurrences" highlighting, but I have not seen anything as drastic as what you show in your screenshots, nor am I able to reproduce it with SQL.  Can you provide specific instructions to reproduce this problem?

**Comment by bojanvukotic** [comment]
Basically that's it. Here are main pieces of my code

	public EditorTextArea()  {
			  super(ROW_COUNT, COLUMN_COUNT);
	}
	
	public void setService(Service service){
		this.service = service;
		setupEditor();
	}

	private void setupEditor() throws IOException {

		this.addParser(new MyErrorParser());
		this.setSyntaxEditingStyle(SYNTAX_STYLE_SQL);

		this.setAnimateBracketMatching(true);
		this.setLineWrap(true);
		this.setAntiAliasingEnabled(true);
		this.setAutoIndentEnabled(true);
		this.setCodeFoldingEnabled(true);
		RSyntaxTextArea.setTemplatesEnabled(true);

		registerCompletionProvider(new String[] {});
		setEditorTheme();
		this.setMarkOccurrences(true);

		registerZoomAction();
		initFindReplaceDialog();
	}

**Comment by bojanvukotic** [comment]
More detailed scenario how to reproduce this: type some text in your text area, click on a word that has a few more occurrences in previously typed text -> few words as marked. Now press ctrl A and than press delete - > text area gets grayed. Quick workaround: in RSyntaxTextArea add following code:

		getDocument().addDocumentListener(new DocumentListener() {

			@Override
			public void removeUpdate(DocumentEvent e) {
				setMarkOccurrences(false);
				setMarkOccurrences(true);
			}

			@Override
			public void insertUpdate(DocumentEvent e) {
				setMarkOccurrences(false);
				setMarkOccurrences(true);
			}

			@Override
			public void changedUpdate(DocumentEvent e) {

			}
		});

This is not nice, but after this is added problem is gone. Problem is that almost all of the mark occurrence classes/fields/methods are private or without access modifier so it can not be sub classed (easily)

**Comment by bobbylight** [comment]
Confirmed, looks like theere's a single root cause for both scenarios.  Both seem to only occur when word wrap is enabled.  Simplest possible reproduction steps:

1. Type some content, place the caret in a word to trigger "marked occurrences."  Select all and hit backspace.  The entire viewport is temporarily all gray - the marked occurrence fills the screen.
2. Type some content, and leave the caret at the end of a word that is marked from "marked occurrences."  Press backspace.  The entire viewport is filled with a "marked occurrence" starting at that word's x-offset.

The cause here comes from RSTA's finagling of `javax.swing.text.Highlight` end-offsets.  Certain highlights, such as those used by marked occurrences, we purposely set their end-offsets as `actualEndOffset - 1` to avoid certain Swing issues.  Then, when actually painted, the painter knows to add ` to the length when rendering.  This logic breaks down when a marked occurrence's end offset is at the end of the `Document`.  The fix appears relatively straightforward, we can cap these highlights' end-offsets at `Math.min(endOffs, endOfDocument)`.
