### ISSUE TITLE
Tokenmaker adoption does nothing

### ISSUE THREAD

**Issue by tttwang23** [bobbylight/RSyntaxTextArea#206]
I have a token maker that requires a non-default constructor.  When I tried to create a text area with the following sequence my custom token maker ends up not adopted.  RSyntaxTextArea version 2.6.0.

final RSyntaxDocument rdoc = new RSyntaxDocument(SyntaxConstants.SYNTAX_STYLE_NONE);
rdoc.setSyntaxStyle(new CashFlowTokenMaker(myCashFlowObj));
textArea = new RSyntaxTextArea(rdoc);

I have to use the following work-around to get my token maker adopted:

final RSyntaxDocument rdoc = new RSyntaxDocument(SyntaxConstants.SYNTAX_STYLE_NONE);
textArea = new RSyntaxTextArea(rdoc);
rdoc.setSyntaxStyle(new CashFlowTokenMaker(myCashFlowObj));

**Comment by bobbylight** [comment]
Cleaning up old tickets - this is now fixed.

I know this wouldn't work in your case due to your `TokenMaker` instance taking parameters in its constructor, but for folks eho stumble upon this ticket in the future: note that in the typical case (your custom `TokenMaker` doesn't take any parameters in its constructor), a good pattern to follow is to update the default `TokenMakerFactory`:

```java
// During general app initialization:
AbstractTokenMakerFactory tmf = (AbstractTokenMakerFactory)TokenMakerFactory.getDefaultInstance();
tmf.putMapping("text/cashFlow", "com.myapp.CashFlowTokenMaker");

// Then your app is aware of the mapping you provided and your TokenMaker is available like so:
RSyntaxTextArea textArea = new RSyntaxTextArea();
textArea.setSyntaxStyle("text/cashFlow");
```
