### ISSUE TITLE
where is forum?

### ISSUE THREAD

**Issue by VaclavSal** [bobbylight/RSyntaxTextArea#209]
The home page returns bad link when accessing forum. 
I do not want to bother developers / coders , been burn few times elsewhere doing  that, but like to learn  more about optioning this tool - especially in A...ino  "IDE". 
Checked souceforge (?) it looks dead. 
So is there an active place to vent? 
Jim

**Comment by bobbylight** [comment]
The forums were overrun by spam, and phpbb has no real good spam solution (or at least, not one that someone like myself, who wants to spend no time maintaining it).  So all questions should be asked here on GitHub.  The good news is, your questions will get much more visibility here anyway.  :)

**Comment by Jimw338** [comment]
Does GitHub have a feature to have separate discussion forums, one for a "developer's forum" and the other a "user's forum"?  (Or would that defeat the purpose of trying to weed out to scourge that is spam?  Is there "GitHub Spam"?)  I have a question (posted the forums as "Getting per-line token count, linked list"), and I'd imagine there are plenty of other "newbie" questions.  These could make feature requests, etc "active-developer discussions" "disappear in the weeds".  The same thing on the wiki - since they don't seem to have comment pages like "The One Wiki To Rule Them All" that is Wikipedia.

I also wonder (also in separate topic) whether there are plans - or if it's really possible - to make a Swift version for iOS/maOS (possibly based on a J2ObjC port).  Since it looks like it depends a lot on TextArea KeyEvent callbacks and such - I don't know at all how those are implemented in Swift.
