### ISSUE TITLE
TextEditorPane/Dirty Issues

### ISSUE THREAD

**Issue by RobertBColton** [bobbylight/RSyntaxTextArea#211]
I have been using RSyntaxTextArea to create an experimental drag and drop based code editor. I've noticed a couple of issues I would like to share.

* For TextEditorPane the load methods create undo's for each line loaded, really the method should have no undo's available.
* There is no property change event for when the charset changes for TextEditorPane which would be useful for updating a status bar.
* FileLocation does not have a property change event for when the file is modified outside of the editor. This would be a useful event to display a confirmation dialog to reload which is how Notepad++ handles this situation.
* Is dirty does not reflect the file being changed outside of the editor. However I still believe this should be an optional feature because people may listen for such an event on their own to display a dialog similar to that I previously mentioned in Notepad++. The dirty property also does not reflect when changes have been undone via the undo manager and the editor is no longer dirty.
* TextEditorPane also lacks a newFile() or createNew() or reinitialize() to set the editor back to a new file.
* RecordableTextAction only handles RTextArea and not other Swing components. The purpose of TextAction in Swing is that it will perform its operations on the focused text editing component through a controller.
https://docs.oracle.com/javase/7/docs/api/javax/swing/text/TextAction.html
Perhaps when the focused text component is not an RTextArea it could call the TextAction.super method to enable the actions to work with other Swing text components instead of doing nothing? However, this may be problematic when it comes to enabling/disabling the actions, but I am sure that can be worked around as well.

**Comment by bobbylight** [comment]
The second bullet point was addressed in commit dbf8308.  I'll take a look at some of the others shortly.

**Comment by bobbylight** [comment]
For the second bullet, only 1 undo was in the undo buffer when calling load(), one for the entire document.  That is no longer the case.

**Comment by bobbylight** [comment]
After addressing two of the issues here, I'm going to close this ticket; please open separate tickets for individual issues you'd like to discuss.

Listening for outside changes would be nice, but is not too high on my todo list, as applications I use RSTA in already have other means of doing this.  I'm still open to the idea of this library supporting it though, and pull requests are welcomd.

I'm a little less concerned about the RecordableTextAction class not doing anything with non-RTextArea instances.  I'm not sure there is a "super", RTextArea-agnostic method we can call, and I'm not sure of the best way to design RecordableTextAction so that an action designates if it can even work on a non-RTextArea text component or not (for example, UndoAction won't work outside of RTextArea since not all text components have undo managers).  Again though, pull requests are welcome.
