### ISSUE TITLE
Add Eclipse Editor features

### ISSUE THREAD

**Issue by OllisGit** [bobbylight/RSyntaxTextArea#214]
I like the RSyntaxTextArea, but I missed some features from my daily IDE

- Multiline movement: Single line is already implemented. How about multiline movement?
- Multiline clonement: Selected lines should be cloned via CTRL + ALT + Arrow Up/Down
- MarkOccurrences for all selected words: At the moment it must be a "identifier" from the enabled programming language. What about double click to hightlight a word and the makr all words in the document
- realtime renaming: if renaming action is executed the selected word should be renamed while typing and other occured equals word should also be renamed

I thing the first two point should be implemented very easy.
What do you think?

Cheers
Olli

**Comment by bobbylight** [comment]
I've addressed multi-line movement in commit 6eaee9c.

For cloning lines via ctrl+alt+arrows, I won't be implementing this, but pull requests are welcome.  I would note that ctrl+alt+arrows is probably not the best keyboard shortcut, since that maps to changing monitor orientation on Windows by default.

For marked occurrences, it's language-specific what token types will have their occurrences marked.  This is because token styles might be used for reasons other than their original intent on a language parser-by-language parser basis.  What token types to highlight is handled via the `TokenMaker.getMarkedOccurrencesOfTokenType(int type)` method.  Is there a particular language that you think occurrence marking should be improved for?

Renaming of fields, etc. is out of scope of RSTA itself, since it requires semantic knowledge of the language being edited, and RSTA doesn't do that.  A blind search-and-replace of a token might replace values that aren't that "variable", for example.

In any case, since one bullet point in this issue was addressed, I'm closing this track.  Feel free to submit a pull request if you do work for any other items.
