### ISSUE TITLE
Does not support in JavaFX Tab

### ISSUE THREAD

**Issue by onkar27** [bobbylight/RSyntaxTextArea#235]
RSyntaxTextArea cannot be convert into node

**Comment by bobbylight** [comment]
I ran into this awhile ago, see this blog post I wrote about it:

http://fifesoft.com/blog/?p=837

I could not figure out what the problem was, except that perhaps it was some kind of Swing/JavaFX integration bug.  I'm not sure what RSTA could be doing "wrong," but suggestions are welcome!  I'd like RSTA to be embeddable in javaFX apps.

**Comment by onkar27** [comment]
i was solved that issue by taking swingnode in tabs context

**Comment by bobbylight** [comment]
Closing per @onkar27's comment.
