### ISSUE TITLE
Support text with attributes

### ISSUE THREAD

**Issue by konopiux** [bobbylight/RSyntaxTextArea#237]
I need a possibility to add text with attributes like it can be done in JTextPane using StyledDocument. Moreover, text with attributes should be underlined. As RSyntaxArea is based on JTextArea and RSyntaxDocument is Subclass of PlainDocument, I don't know how to implement such functionality. 
Maybe someone can give any suggestions how it can be done in RSyntaxTextArea?

**Comment by bobbylight** [comment]
Unfortunately, this cannot be done.  Styles can only be applied from the installed SyntaxScheme, and cannot be added programmatically.  There is a branch where I experiemented with converting from the current architecture to StyledDocument:

https://github.com/bobbylight/RSyntaxTextArea/tree/using-DefaultStyledDocument

But it's buggy, and also hasn't been rebased on master in months.  Honestly, I doubt I'll ever convert RSTA to use StyledDocument, because there's very little reason to do so.  RSTA is less memory-hungry because of our current rendering architecture.
