### ISSUE TITLE
Help with implementing syntax coloration

### ISSUE THREAD

**Issue by Zezombye** [bobbylight/RSyntaxTextArea#242]
Hi, since the forum is closed I'll ask my question here.

I can't seem to properly implement the TokenMaker. I declared a class SyntaxColoration extending AbstractTokenMaker, implementing the required methods (getTokenList and getWordsToHighlight) given in the example. Then I set it for my text pane with:
```
AbstractTokenMakerFactory atmf = (AbstractTokenMakerFactory)TokenMakerFactory.getDefaultInstance();
		atmf.putMapping("test/zezLang", "zezombye.Project.SyntaxColoration");
		this.setSyntaxEditingStyle("text/zezLang");
```
SyntaxColoration is in the package zezombye.Project so it should be the right string.
However there seems to be no syntax coloration at all, when I type a string or a number it doesn't do anything.
Where did I go wrong?

Also, is there a way to use regexes? This would be way easier for me given that I already used them before.
Thanks.

**Comment by Zezombye** [comment]
I did a workaround by generating a TokenMaker with Jflex 1.4.1 (1.6.1 doesn't work), replacing JavaTokenMaker.java by my TokenMaker, then setting the coloration to SYNTAX_STYLE_JAVA.

**Comment by bobbylight** [comment]
This sounds like the right approach.  Make sure your SyntaxColoration class was indeed on the classpath.

For others (since it looks like you found the documentation), the doc for this is in the wiki here:  [Adding Syntax Highlighting for a new Language](https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding-Syntax-Highlighting-for-a-new-Language).

I'm closing this due to its age, but feel free to reopen if you still have a problem and would like more help with it.
