### ISSUE TITLE
RSyntaxTextArea does not recognize CRLF line terminator.

### ISSUE THREAD

**Issue by olegvasylenko** [bobbylight/RSyntaxTextArea#251]
Case: we want to edit e text which contains CRLF line terminator.

Step to reproduce:
1. put cursor in the middle of a line;
2. press END key.
3. type several symbols.
4. Get text from RSyntaxTextArea and save it to file.

Open file in Notepad++ and enable line terminator symbols to be displayed.

Result: The symbols from step 3 will by between CR and LF and would be at new line.

Problem here: When you add some comment in JavaScript Code at single line comment end in fact it produces two lines and the second line is not a comment anymore.
The script fails runtime but in editor you don't see the problem as the new text still displayed in the single line comment. 

It may have other side-effect to different languages....

**Comment by bobbylight** [comment]
Being a standard Swing `JTextComponent`, RSTA expects normalized line endings - either all LF or all CRLF pairs.  Further, it expects its internal document model to only contain LFs for line endings, otherwise you end up with nasty bugs like what you've described.

To avoid this issue, it's recommended that you normalize line endings to LF when loading text into RSTA (and all JTextComponents).  An easy way to do this is with the [JTextComponent.read](https://docs.oracle.com/javase/7/docs/api/javax/swing/text/JTextComponent.html#read(java.io.Reader,%20java.lang.Object)) method.  Alternatively, if you're using `org.fife.ui.rsyntaxtextarea.TextEditorPane` for its editor-ish features, you can call `load(FileLocation)` (which will result in a `JTextComponent.read()` method under the covers).

The only issue this causes is if you want to keep your file containing a heterogeneous mixture of line terminators (some CRLF, some just LF).  This is a pretty uncommon desire however, and can't really be worked around when using Swing JTextComponents, thus RSTA has no support for it either.  But as long as you're OK with the component standardizing line terminators, you should be OK with one of the options listed above.
