### ISSUE TITLE
How set the content fragment color

### ISSUE THREAD

**Issue by liujingjing5** [bobbylight/RSyntaxTextArea#262]
For example, the rsyntaxtextarea content is "hello",the color is default black.
but I want the middle character "ell", it`s color change to red.
how can i do?

maybe SearchEngine.markAll() can be done， but i don`t want use markAll()
because at next markAll() , the style will cleared

thank u~

**Comment by bobbylight** [comment]
You can't style arbitrary spans of characters.  RSTA is only capable of styling text based on a lexer that parses text as a programming language.  If you have a set of rules you want to follow (vs. just arbitrary coloring), you can follow the instructions [here](https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding-Syntax-Highlighting-for-a-new-Language) to create a lexer for your "language", and RSTA will highlight it.  Otherwise, for arbitrary styling like in MS Word, you might consider looking up demos on `JTextPane` or `JEditorPane`, which support that.
