### ISSUE TITLE
How to make the editor read-only / view only?

### ISSUE THREAD

**Issue by johann-petrak** [bobbylight/RSyntaxTextArea#328]
Is there a way to show code in the RSyntaxTextArea in the same way as usual, but without any ability to edit and change anything?

Bonus question: is there some user forum or mailing list? This is an extremely useful library but the documentation seems to cover only a small portion of what the library can actually do and I find it very hard to figure out the rest just from the JavaDocs.

**Comment by bobbylight** [comment]
You're looking for `textArea.setEditable(false)`, or possibly `textArea.setEnabled(false)`, though the former is typically better since you likely want to allow copy-paste, and `setEnabled` prohibits that.

As for forums, there used to be; I ran a simple forum that had a mild amount of traffic.  However, it eventually got overrun with spam and no spam prevention methods I put in place seemed to remedy things.  So I got rid of it in lieu of simply using the GitHub issue tracker you're on now along with the [wiki](https://github.com/bobbylight/RSyntaxTextArea/wiki).  If you have features or things you think would be useful to add a wiki entry for, let me know and I can cobble one together.
