### ISSUE TITLE
dealing with french accents

### ISSUE THREAD

**Issue by mbrebion** [bobbylight/RSyntaxTextArea#341]
Hi, 
I've made a custom latex tokenMaker by using jflex. Everything works fine with it.
I've recently try to add the spell-checking feature with a french dictionary and it also seems to work correctly. However, I've figured out that words with accents like "forêt" or "abaissée" are split into three tokens. One before the accented characters, one for this letter and for the remaining characters.

This is the part of the flex file I use :
```
Letter					= ([A-Za-z])
Accent                                   = (éèêëùàâû)
Digit					= ([0-9])
LetterOrUnderscore		= ({Letter}|[_])
AnyChar					= ({LetterOrUnderscore}|{Digit}|[\-]|{Accent})
```

(I also get the same problem without declaring explicitely the Accent sequence of characters)
So is my problem caused by a problem in the flex file or is it specific to RSyntaxTextArea ?

Thanks in advance
Maxence

**Comment by mbrebion** [comment]
For the moment, I've found a fix which consist in redefining Letter by hand :
```
Letter					= ([azertyuiopmlkjhgfdsqwxcvbnAZERTYUIOPMLKJHGFDSQWXCVBNéèêëàâùûüöô])
```
Is still don't understand my previous error but I'm ok with this fix

**Comment by bobbylight** [comment]
You left out where you use AnyChar, are you defining words like this (or similar)?

`{AnyChar}+`

**Comment by mbrebion** [comment]
Yes I do : 
```
/* Catch any other (unhandled) characters and flag them as identifiers. */
	{AnyChar}+						{ addToken(Token.IDENTIFIER);  }
        .							        {  addToken(Token.IDENTIFIER);  }
```

**Comment by bobbylight** [comment]
Sorry for the late reply, I've been neglecting this project.  I think I see the issue in your original Flex snippet - Your "Accent" rule was in parent not square brackets, which would cause it to look for the string literal containing all of those accented characters together as a group, rather than any individual one:

```
Accent                                   = (éèêëùàâû)
```

Should be:

```
Accent                                   = ([éèêëùàâû])
```
Can you confirm this fixes it for you as well?  Or if you are satisfied with your other workaround, feel free to close this ticket as well,
