### ISSUE TITLE
Gradle broken again

### ISSUE THREAD

**Issue by orbitalair** [bobbylight/RSyntaxTextArea#349]
Can this project get off gradle and just have a build.xml file?

I got a new win10 install on a clean harddrive, I installed JDK 14 and Netbeans 11 and out of the box gradle doesnt work - again.   When I look up the gradle error message theres a long list that goes all the way back to November of last year of gradle NOT working for anyone.  

Otherwise I suggest you always test with a clean install of gradle and the jdk AND provide a page of instructions on how to get around all the problems.

thanks for reading.

**Comment by orbitalair** [comment]
Followup info.  Resolved for now.

Apparently even tho your gradle desc has 6.4.1., Netbeans 11.3 64bit installs 6.4.1. yet still fails to build.
  
I had to go to Tools->Options->Java tab->gradle tab, then change the selection to Gradle version 6.5.   Netbeans thens installs yet another copy of gradle into my user account location /.gradle (more aggravation).

Another option on that tab is to use a location you specify, using a gradle you install yourself.

Thanks for reading.

**Comment by bobbylight** [comment]
Interesting, I haven't heard of folks having issues with the gradle build before.  Can you provide a link to the thread about the Gradle issue you mention?  Is it a gradle issue, or Gradle/NetBeans integration?

**Comment by orbitalair** [comment]
Hi,

First I posted a followup comment to clarify that it does work with gradle
6.5.  Thankfully, because I love this project.  It has helped me a lot.

Heres the link;  https://github.com/gradle/gradle/issues/10248
this was the search I did using the error message;  'gradle Could not
initialize class org.codehaus.groovy.reflection.ReflectionCache'

It appears to be a Gradle/JDK set of issues.  I gather that Oracle keeps
changing the JDK, and gradle was using a public call that is now private
(or gone).

I ran into a gradle problem years ago when they updated, and then my
netbeans quit compiling this project.  To me its frustrating because I keep
sources close due to the long term nature of our projects (we have them
going on 20 years old now), I like to be able to rebuild everything from
sources.  So things like gradle breaking itself is...well, not nice.

Oracle and Netbeans updating every 4 months now is quite a ridiculous pain
in the rear end.  Its fun for OPenSource, but not for the Corporate arena.

Thanks again and I hope to contribute to the project in some way in the
future.

Joe Robertson
orbitalair@gmail.com

**Comment by bobbylight** [comment]
Yeah, I feel you on reproducible builds.  I feel it all the time with node webapps/frontends - the JS community truly is a house of cards!

I pin my builds (both locally and the CI builds) to use JDK8, so I've never run into this issue.  This may not be a possibility for you, but it's worth mentioning - the official builds on Maven Central are built with Java 8 so Java 9+ is not a requirement for consumers.  As an aside, if you build with Java 9+ you'll get a crapton of warnings due to Oracle deprecating API's we use - I'll clean those up once I update RSTA to require a newer Java version (not on my immediate radar, but if a JRE release actively *removes* any of the API's we're using it'll force my hand).

Is this is a corporate project, is there any reason you're not fetching RSTA (and other dependency) builds from Maven Central?  I'd imagine every dependency has different build requirements (Maven vs. Gradle vs. Ant, Java versions, etc.) and using something like Maven or Gradle gives you an easy way to scan for e.g. security vulnerabilities in dependencies so you know when you should upgrade.

**Comment by orbitalair** [comment]
Hi,

No maven or anything like that.

Couple of reasons.  I dont want to depend on the internet.  Its too fluid.
I've seen things vanish too many times.
Another is corporate firewalls like zscalar and internal crap like
bitblocker play havoc with internet stuff.

Our process is based on internal version control systems as the prime, so I
get code, test it, vett it, etc and then place in our own VM
We work security issues in the same way, updating by hand, testing,
vetting, then putting into our own VM.

Our product is still JDK8 based (some are still using JDK6), and my work
setup is still netbeans 8.2 and jdk8.

But my home dev env is updated to the latest netbeans and jdk, so I could
see what was different.

Thanks,
Joe

**Comment by bobbylight** [comment]
Closing since this was a gradle/JDK issue, not an RSTA issue.
