### ISSUE TITLE
What is a good way to add own tokens?

### ISSUE THREAD

**Issue by dzmipt** [bobbylight/RSyntaxTextArea#365]
I want to define syntax highlighting for a language which is not currently supported.

I implemented TokennMarker interface and added full set of own Token types. However I found that matching brackets are not highlighted. Then I investigated source code and I realised that the code is coupled with concrete token types - (if I read it correctly) it is supposed that brackets should be marked with TokenType.SEPARATOR. Reading deeply, I found hardcoding on other token types.

So it looks I have two options:
1) Fork the code and fix everything in my repo
2) Be limited with existent token types (with probably some additions)

So my question: are my conclusions correct? May be a refactoring of the component will be performed to decouple the hardcoding?

**Comment by bobbylight** [comment]
Yes, you're correct about the SEPARATOR assumption in RSTA.

Can you explain why this is a problem?  e.g. why you can't create bracket/brace tokens as TokenType.SEPARATOR?  

One concern I have about refactoring things to remove this limitation is that this assumption might be littered across many files instead of centralized (been a while since I looked so I could be wrong though).  Admittedly though "SEPARATOR" is a little bit generic of a token type, and it would be nice to have one specific to brackets, or perhaps some property of a token that flags it as a block-scope delimiter, regardless of its type.

**Comment by dzmipt** [comment]
One of the problem is that it wasn't obvious. I understand that there are already a lot of code. So i would suggest to at least add some comments to TokenTypes interface to how various ids are used (coupled w/ other logic across RSTA).

For me, it wasn't obvious originally what SEPARATOR is. Therefore I created my own BRACKET id and debugged for some time to understand why bracket matching didn't work. Changing id to SEPARATOR solved the problem for me.

**Comment by bobbylight** [comment]
I've added some comments to this effect, thanks.  Making the API a little more robust probably won't happen until a 4.x release.
