### ISSUE TITLE
Adding Words to highlight during runtime

### ISSUE THREAD

**Issue by omegaui** [bobbylight/RSyntaxTextArea#368]
I have created a java IDE using this amazing library as the Editor (see https://github.com/omegaui/omegaide ).

I want to highlight different type of variables with different colors as the programmer types into the Editor like the static members with green or anyother color.

How can I do that during runtime of the IDE?

**Comment by bobbylight** [comment]
Semantic highlighting isn't supported by any of the built-in languages in RSTA.  There's no reason you couldn't build it yourself but you'd have to write your own `TokenMaker` instance to do so (see [Adding Syntax Highlighting for a new Language](https://github.com/bobbylight/RSyntaxTextArea/wiki/Adding-Syntax-Highlighting-for-a-new-Language) for more information).

One project that may be helpful is [RSTALanguageSupport](https://github.com/bobbylight/RSTALanguageSupport).  That library doesn't add semantic highlighting, but it does add code completion and other advanced features for a few languages, including Java.  Unfortunately its Java support may have some outdated aspects, e.g.  it parses the API out of the JDK's rt.jar for code completion purposes and so that aspect doesn't work right in Java 9+ since they changed the structure of the JDK with modules.  :(

I know other folks have added semantic highlighting into RSTA for other projects.  The one that comes to mind for me is [Squirrel SQL](http://www.squirrelsql.org/) whichm, if I recall correctly, colorizes valid column names in SQL queries with a unique color.  They're open source so it might be worth checking that project out as well,.

**Comment by omegaui** [comment]
@bobbylight . Well, I only wanted to add more colors to the editors. I have already created a code completion mechanism. Thank You, I will look into writing a custom Highlight Painter for the editor that's the only thing left to try, if not then JavaFX's RichTextFX (Embed Swing)

**Comment by omegaui** [comment]
@bobbylight  One more thing, please add syntax highlighting for RUST-Lang also, it would be a great upgrade.⚡⚡⚡👍🏻👍🏻👍🏻

**Comment by omegaui** [comment]
Its quite late but

There's a quick solution....
- Use RSTA from sources
- Change `getBackgroundForToken`, `getForegroundForToken` or `getFontForTokenType` in `RSyntaxTextArea.java` to acheive runtime dynamic coloring

Example

ALL uppercase words are highlighted dynamically as the user types

![Screenshot from 2022-02-23 17-05-14](https://user-images.githubusercontent.com/73544069/155311910-49d20470-c837-44f1-9166-9cc80e7b10a9.png)
