### ISSUE TITLE
Bracket pairs don't repaint on font changes

### ISSUE THREAD

**Issue by DeflatedPickle** [bobbylight/RSyntaxTextArea#395]
I added a zooming function to my `RSyntaxTextArea` which was achieved by changing the font to one bigger/smaller than the last. However upon using it, I noticed that the blue highlight over bracket pairs do not repaint for the new size, but other parts such as the line numbers do repaint
![Peek 2021-07-25 08-36](https://user-images.githubusercontent.com/24986480/126892063-347e2d4f-ec83-4e29-9aa7-05bdce1429a4.gif)

**Comment by bobbylight** [comment]
Thanks for the bug report!  This is fixed in the latest 3.1.4-SNAPSHOT on Sonatype.

Also note that calling `setFont()` only works if you only use a single font + size in your editor (bold and italics are OK).  If you ever use multiple different fonts for different token types (I know this isn't a common thing to do, but it is supported), you'll have to use `RSyntaxTextAreaEditorKit.IncreaseFontSizeAction` and `RSyntaxTextAreaEditorKit.DecreaseFontSizeAction` for this operation (or write a lot more code yourself).
