### ISSUE TITLE
Garbage is left from cursor on VK_DOWN

### ISSUE THREAD

**Issue by dzmipt** [bobbylight/RSyntaxTextArea#404]
I spot that during clicking on arrow down key, garbage is left on previous lines (see below screenshot from the Demo app). When I resize the frame (I assume during paint), the garbage disappears. VK_UP doesn't have such effect.
I am using MacOS 11.4;  jdk1.8.0_251.jdk.
![image](https://user-images.githubusercontent.com/29353814/134778965-df2586d1-0577-42fd-9ea5-bd574b60231b.png)

**Comment by bobbylight** [comment]
Can you debug and inspect the font being used (family, size, any other interesting tidbits?).  I'm assuming it's the default (Menlo or Monaco or something similar) but just so I have the data point.  This looks like a regression though I can't reproduce it.  The fix is likely changing the caret height to be 1 pixel shorter.

Also, does the overwrite cursor do the same thing?

**Comment by dzmipt** [comment]
javax.swing.plaf.FontUIResource[family=Menlo,name=Menlo,style=plain,size=12]

**Comment by dzmipt** [comment]
textArea.getFont() returns
javax.swing.plaf.FontUIResource[family=Menlo,name=Menlo,style=plain,size=12]

Adding
textArea.setTextMode(RTextArea.OVERWRITE_MODE)
into the code will give me a block cursor. But the garbage is not left with such cursor

**Comment by dzmipt** [comment]
Changing ConfigurableCaret.java (lines 474-479) to this (decreasing caret height by one pixel) fixed the issue for me: 
					// A thicker vertical line.
					case THICK_VERTICAL_LINE_STYLE:
						g.drawLine(r.x,r.y+1, r.x,r.y+r.height);
						r.x++;
						g.drawLine(r.x,r.y+1, r.x,r.y+r.height);
						break;
