### ISSUE TITLE
Update the Community Profile!

### ISSUE THREAD

**Issue by omegaui** [bobbylight/RSyntaxTextArea#422]
![Screenshot from 2021-12-31 11-30-57](https://user-images.githubusercontent.com/73544069/147806360-33812261-2dff-44ee-a989-39f41780ec7c.png)

The repo is missing LICENSE.md which is critical.

**Comment by ThexXTURBOXx** [comment]
It's not really missing. It's just not where you would expect it to be: https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/dist/RSyntaxTextArea.License.txt

**Comment by bobbylight** [comment]
The license has been moved to the root directory and I've added templates for bug reports and feature requests.  Cuurrently I don't see much value in adding a code of conduct or a CONTRIBUTING file since very few folks actually contribute to this repository.  Hopefully the changes made will help standardize tickets and make the license more obvious.
