### ISSUE TITLE
Foreground color for colon(:) and comma(,) in json syntax

### ISSUE THREAD

**Issue by VikasTiwari199915** [bobbylight/RSyntaxTextArea#527]
I am trying to color the : and , in a json string,
i have tried almost all Token Types but wasn't successful.
The background for the TextArea is very dark and the colon and comma are black, so they are barely visible.

How can i choose a custom color for these two symbols?

i have colored other parts of the json like this :
```
scheme.getStyle(Token.SEPARATOR).foreground = new Color(97, 221, 253);
//same code for other TOKENS like VARIABLE..
```
![IMG_20240112_153856.jpg](https://github.com/bobbylight/RSyntaxTextArea/assets/44534116/68abe542-891d-470d-8173-1df9e5759248)

**Comment by shinobisoft** [comment]
View the wiki [here](https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Setting-the-theme#setting-individual-fonts-and-colors-via-the-api)

**Comment by bobbylight** [comment]
`:` in JSON is [rendered as a TokenTypes.IDENTIFIER](https://github.com/bobbylight/RSyntaxTextArea/blob/master/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/modes/JsonTokenMaker.flex#L288), so you should be able to update that style for JSON. I know that sounds a little odd, and it is, but I think it's because it's a token type not used elsewhere for JSON. Feel free to open a PR if you would like to be a different token type.
